name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.8.0]

    steps:
    - uses: actions/checkout@v2

    - name: Install packages
      with:
        cmd: yarn install

    - name: Setup test DB
      env:
        FAUNADB_ADMIN_SECRET: ${{ secrets.TEST_FAUNADB_ADMIN_SECRET }}
      with:
        cmd: yarn test:setup    

    - name: Run tests
      env:
        FAUNADB_ADMIN_SECRET: ${{ secrets.TEST_FAUNADB_ADMIN_SECRET }}
      with:
        cmd: yarn test
